export enum NavigationNames {
  Home = "Home",
  Login = "Login",
  Dashboard = "Dashboard",
  Welcome = "Welcome",
  Info = "Info",
  Detail = "Detail",
  Settings = "Settings",
  Willy = "Willy",
  Demo = "Demo",
  CounterScreen = "CounterScreen",
  RandomColor = "RandomColor",
  SquareScreen = "SquareScreen",
  TextScreen = "TextScreen",
  SearchScreen ="SearchScreen",
}
